### ISSUE TITLE
Не запускать NextGIS Web в случае, если адрес занят

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb_qgis#1]
Ситуация следующая. Запускаю ngw через pserve, по Ctrl+C у меня не выходит, прибиваю по Ctrl+Z, но при этом процесс остаётся, если еще раз запустить (не убивая предыдущий процесс), то запускается еще один (хотя пишет, что Address already in use) и так далее. Если nextgisweb_qgis не используется, то в подобной ситуации выводится Address already in use и процесс не создаётся.

**Comment by dezhin** [comment]
Странно, по Ctrl+C у меня он все-таки в любом случае завершался. Остальное я вроде бы поправил, оказалось все просто.
