### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by cfdbwrbq** [nextgis/nextgisweb_qgis#11]
Привет.
`git clone git@github.com:nextgis/nextgisweb_qgis.git`
выдает ошибку
`Cloning into 'nextgisweb_qgis'...
Permission denied (publickey).
fatal:
Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.`

а вот `git clone https://github.com/nextgis/nextgisweb_qgis.git` работает как надо

**Comment by simgislab** [comment]
любой другой репозиторий (не обязательно от нас) вы соответственно тоже не можете ниоткуда склонировать через git, верно?

**Comment by cfdbwrbq** [comment]
нет. 
`git clone https://github.com/nextgis/nextgisweb_mapserver.git` клонируется без вопросов.

**Comment by simgislab** [comment]
перечитайте мой вопрос внимательно

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/docs_ngweb/commit/734ea97759c8783d12df0d0bd1f9df9f08d6f988

**Comment by cfdbwrbq** [comment]
ошибся, сорри.
да. видимо так никакой не клонируется.
