### ISSUE TITLE
NGW не запускается после установки NextGIS Web QGIS

### ISSUE THREAD

**Issue by cfdbwrbq** [nextgis/nextgisweb_qgis#12]
локальный сервер `Ubuntu 16.04`
`Qgis `установлен
запускаю через `pserve`
пишет:
> Traceback (most recent call last):
  File "env/bin/pserve", line 11, in <module>
    sys.exit(main())
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 229, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/__init__.py", line 65, in main
    env = Env(cfg)
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/env.py", line 21, in __init__
    components_ignore=components_ign)
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/component.py", line 99, in load_all
    __import__(pkginfo.comp_mod(comp))
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/wmsclient/__init__.py", line 3, in <module>
    from .model import Base, Connection, Layer, WMS_VERSIONS
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/wmsclient/model.py", line 14, in <module>
    from owslib.map.common import WMSCapabilitiesReader
ImportError: No module named map.common

**Comment by drnextgis** [comment]
Какая версия OWSLib? Покажите вывод `pip freeze`.

**Comment by cfdbwrbq** [comment]
> (env) gisolog@mapserver:~/ngw$ pip freeze
Babel==2.6.0
bunch==1.0.1
certifi==2018.4.16
chardet==3.0.4
flufl.enum==4.1.1
GeoAlchemy2==0.4.2
geojson==2.4.0
hupper==1.3
idna==2.6
ipaddress==1.0.22
lxml==4.2.1
Mako==1.0.7
MarkupSafe==1.0
minio==4.0.0
-e git+https://github.com/nextgis/nextgisweb.git@8340bdb80fe0e30810ba796a91bed758baa69f4f#egg=nextgisweb
-e git+https://github.com/nextgis/nextgisweb_mapserver.git@31d7585e01635488356cbd4db563a86f79734cb4#egg=nextgisweb_mapserver
-e git+https://github.com/nextgis/nextgisweb_qgis.git@621b037839c97a9f6fc5b68b4dbe62b975a6613f#egg=nextgisweb_qgis
numpy==1.14.3
OWSLib==0.16.0
passlib==1.7.1
PasteDeploy==1.5.2
Pillow==5.1.0
plaster==1.0
plaster-pastedeploy==0.5
ply==3.11
psycopg2==2.7.4
pygdal==2.2.1.3
Pygments==2.2.0
pyproj==1.9.5.1
pyramid==1.9.2
pyramid-debugtoolbar==4.4
pyramid-mako==1.0.2
pyramid-tm==2.2
python-dateutil==2.7.3
pytz==2018.4
repoze.lru==0.7
requests==2.18.4
Shapely==1.6.4.post1
six==1.11.0
SQLAlchemy==1.2.8
transaction==2.2.1
translationstring==1.3
unicodecsv==0.14.1
urllib3==1.22
venusian==1.1.0
waitress==1.1.0
WebOb==1.8.1
zope.deprecation==4.3.0
zope.interface==4.5.0
zope.sqlalchemy==1.0

**Comment by drnextgis** [comment]
У меня при той же версии всё работает:

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from owslib.map.common import WMSCapabilitiesReader
>>> 
(env) rykov@work:~$ pip freeze | grep OWSLib
OWSLib==0.16.0
```

**Comment by cfdbwrbq** [comment]
Странное. 
Попробую все переустановить с нуля.
> gisolog@mapserver:~/ngw$ source env/bin/activate
> (env) gisolog@mapserver:~/ngw$ pip install OWSLib
> Requirement already satisfied: OWSLib in ./env/lib/python2.7/site-packages (0.16       .0)
> Requirement already satisfied: pyproj in ./env/lib/python2.7/site-packages (from        OWSLib) (1.9.5.1)
> Requirement already satisfied: pytz in ./env/lib/python2.7/site-packages (from O       WSLib) (2018.4)
> Requirement already satisfied: python-dateutil>=1.5 in ./env/lib/python2.7/site-       packages (from OWSLib) (2.7.3)
> Requirement already satisfied: requests>=1.0 in ./env/lib/python2.7/site-package       s (from OWSLib) (2.18.4)
> Requirement already satisfied: six>=1.5 in ./env/lib/python2.7/site-packages (fr       om python-dateutil>=1.5->OWSLib) (1.11.0)
> Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python2.7/site-pa       ckages (from requests>=1.0->OWSLib) (2018.4.16)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python2.7/site       -packages (from requests>=1.0->OWSLib) (3.0.4)
> Requirement already satisfied: idna<2.7,>=2.5 in ./env/lib/python2.7/site-packag       es (from requests>=1.0->OWSLib) (2.6)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./env/lib/python2.7/site       -packages (from requests>=1.0->OWSLib) (1.22)
> (env) gisolog@mapserver:/ngw$ python
> Python 2.7.12 (default, Dec  4 2017, 14:50:18)
> [GCC 5.4.0 20160609] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
>  from owslib.map.common import WMSCapabilitiesReader
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named map.common
>  quit()
> (env) gisolog@mapserver:~/ngw$ pip freeze | grep OWSLib
> OWSLib==0.16.0

**Comment by cfdbwrbq** [comment]
Привет.
Можно закрывать. Проблема была в том, что Qgis был установлен **_после_** установки NextGIS Web QGIS. Спасибо.
