### ISSUE TITLE
Вчера работало, а сегодня - нет. [решено]

### ISSUE THREAD

**Issue by cfdbwrbq** [nextgis/nextgisweb_qgis#13]
Привет!
И снова случилось странное. 
Все работало без проблем, но сегодня получил
502 Bad Gateway
смотрю логи, а там...
```
[2018-07-05 12:33:36 +0000] [6403] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 50, in load
    return self.load_pasteapp()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 46, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=self.cfg.paste_global_conf)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/gunicorn/app/pasterapp.py", line 71, in load_pasteapp
    global_conf=global_conf)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/__init__.py", line 65, in main
    env = Env(cfg)
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/env.py", line 21, in __init__
    components_ignore=components_ign)
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/component.py", line 93, in load_all
    for pkg in pkginfo.packages:
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/package.py", line 54, in packages
    self.scan()
  File "/home/gisolog/ngw/nextgisweb/nextgisweb/package.py", line 29, in scan
    pkginfo = epoint.load()()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/gisolog/ngw/nextgisweb_qgis/nextgisweb_qgis/__init__.py", line 12, in <module>
    from qgis.core import (
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/qgis/__init__.py", line 27, in <module>
    from qgis.core import QgsFeature, QgsGeometry
  File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/qgis/core/__init__.py", line 30, in <module>
    from qgis._core import *
ImportError: libqgis_core.so.2.18.17: cannot open shared object file: No such file or directory
```
попробовал обновить Qgis...
```
gisolog@mapserver:~/ngw$ sudo apt-get install qgis python-qgis
Построение дерева зависимостей
Чтение информации о состоянии… Готово
Уже установлен пакет qgis самой новой версии (2.18.20+dfsg-1~bionic1).
Уже установлен пакет python-qgis самой новой версии (2.18.20+dfsg-1~bionic1).
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
```
на сервере вообще ничего не делал, кроме, не глядя, `apt-get update && upgrade -y` и все...
как это можно полечить? 
Спасибо.
зы
```
gisolog@mapserver:~/ngw$ env/bin/pip freeze
Babel==2.6.0
bunch==1.0.1
certifi==2018.4.16
chardet==3.0.4
flufl.enum==4.1.1
GeoAlchemy2==0.4.2
geojson==2.4.0
gunicorn==19.8.1
hupper==1.3
idna==2.7
ipaddress==1.0.22
lxml==4.2.1
Mako==1.0.7
mapscript==7.0.7
MarkupSafe==1.0
minio==4.0.0
-e git+https://github.com/nextgis/nextgisweb.git@8340bdb80fe0e30810ba796a91bed758baa69f4f#egg=nextgisweb
-e git+https://github.com/nextgis/nextgisweb_mapserver.git@31d7585e01635488356cbd4db563a86f79734cb4#egg=nextgisweb_mapserver
-e git+https://github.com/nextgis/nextgisweb_qgis.git@621b037839c97a9f6fc5b68b4dbe62b975a6613f#egg=nextgisweb_qgis
numpy==1.14.5
OWSLib==0.16.0
passlib==1.7.1
PasteDeploy==1.5.2
Pillow==5.1.0
plaster==1.0
plaster-pastedeploy==0.5
ply==3.11
psycopg2==2.7.4
pygdal==2.2.3.3
Pygments==2.2.0
pyproj==1.9.5.1
pyramid==1.9.2
pyramid-debugtoolbar==4.4
pyramid-mako==1.0.2
pyramid-tm==2.2
python-dateutil==2.7.3
pytz==2018.4
repoze.lru==0.7
requests==2.19.0
Shapely==1.6.4.post1
six==1.11.0
SQLAlchemy==1.2.8
transaction==2.2.1
translationstring==1.3
unicodecsv==0.14.1
urllib3==1.23
uWSGI==2.0.17
venusian==1.1.0
waitress==1.1.0
WebOb==1.8.2
zope.deprecation==4.3.0
zope.interface==4.5.0
zope.sqlalchemy==1.0
```
```
gisolog@mapserver:~/ngw/env/lib/python2.7/site-packages/qgis$ ls -la
total 23544
drwxr-xr-x   9 gisolog gisolog     4096 июн 13 14:35 .
drwxrwxr-x 105 gisolog gisolog     4096 июн 14 16:32 ..
drwxr-xr-x   2 gisolog gisolog     4096 июн 13 14:35 analysis
-rw-r--r--   1 gisolog gisolog   575736 июн 13 14:35 _analysis.x86_64-linux-gnu.so
drwxr-xr-x   2 gisolog gisolog     4096 июн 13 14:35 core
-rw-r--r--   1 gisolog gisolog 14060352 июн 13 14:35 _core.x86_64-linux-gnu.so
drwxr-xr-x   2 gisolog gisolog     4096 июн 13 14:35 gui
-rw-r--r--   1 gisolog gisolog  8989520 июн 13 14:35 _gui.x86_64-linux-gnu.so
-rw-r--r--   1 gisolog gisolog     1814 июн 13 14:35 __init__.py
-rw-r--r--   1 gisolog gisolog     2130 июн 13 14:35 __init__.pyc
drwxr-xr-x   2 gisolog gisolog     4096 июн 13 14:35 networkanalysis
-rw-r--r--   1 gisolog gisolog   110104 июн 13 14:35 _networkanalysis.x86_64-linux-gnu.so
drwxr-xr-x   3 gisolog gisolog     4096 июн 13 14:35 PyQt
drwxr-xr-x   2 gisolog gisolog     4096 июн 13 14:35 server
-rw-r--r--   1 gisolog gisolog   272024 июн 13 14:35 _server.x86_64-linux-gnu.so
drwxr-xr-x   2 gisolog gisolog     4096 июн 13 14:35 testing
-rw-r--r--   1 gisolog gisolog     3476 июн 13 14:35 user.py
-rw-r--r--   1 gisolog gisolog     3250 июн 13 14:35 user.pyc
-rw-r--r--   1 gisolog gisolog    19243 июн 13 14:35 utils.py
-rw-r--r--   1 gisolog gisolog    17801 июн 13 14:35 utils.pyc
```

**Comment by drnextgis** [comment]
Это из-за того, что вы обновили QGIS, должно [помочь](https://github.com/nextgis/nextgisweb_qgis):

```
$ qgis-to-env env
```

**Comment by cfdbwrbq** [comment]
Спасибо, но не помогло.

```
(env) sudo apt-get remove qgis python-qgis
(env) gisolog@mapserver:~/ngw$ sudo apt-get install qgis python-qgis
(env) gisolog@mapserver:~/ngw$ nextgisweb_qgis/qgis-to-env env
```

> '/usr/lib/python2.7/dist-packages/qgis/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/user.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/user.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/utils.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/utils.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/uic/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/uic/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/uic/properties.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/uic/properties.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/uic/pyuic.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/uic/pyuic.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/Qsci.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/Qsci.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/Qt.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/Qt.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtCore.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtCore.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtGui.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtGui.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtNetwork.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtNetwork.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtPrintSupport.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtPrintSupport.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtSql.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtSql.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtSvg.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtSvg.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtTest.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtTest.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtWebKit.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtWebKit.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtWebKitWidgets.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtWebKitWidgets.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtWidgets.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtWidgets.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/QtXml.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/QtXml.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/PyQt/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/PyQt/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/analysis/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/analysis/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/core/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/core/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/core/contextmanagers.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/core/contextmanagers.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/gui/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/gui/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/networkanalysis/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/networkanalysis/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/server/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/server/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/testing/__init__.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/testing/__init__.pyc'
> '/usr/lib/python2.7/dist-packages/qgis/testing/mocked.pyc' -> '/home/gisolog/ngw/env/lib/python2.7/site-packages/mapscript.egg/qgis/testing/mocked.pyc'

> (env) gisolog@mapserver:~/ngw$ python
> Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
> [GCC 7.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import qgis
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/qgis/__init__.py", line 27, in <module>
>     from qgis.core import QgsFeature, QgsGeometry
>   File "/home/gisolog/ngw/env/local/lib/python2.7/site-packages/qgis/core/__init__.py", line 30, in <module>
>     from qgis._core import *
> ImportError: libqgis_core.so.2.18.17: cannot open shared object file: No such file or directory
