### ISSUE TITLE
Другой способ инициализации

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb_qgis#3]
Вот [тут](https://hub.qgis.org/issues/13494) пишут, что вроде правильный способ инициализации отличается от того, что используем мы. Я попробовал заменить:

```
QgsApplication.initQgis()
qgis = QgsApplication([], False)
```
на
```
qgis = QgsApplication([], False)
qgis.initQgis()
```

но после этого, вообще ничего не рендерится.

**Comment by yellow-sky** [comment]
Я не уверен, что второй вариант правильный. 
http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/intro.html#using-pyqgis-in-custom-application
Тут говорится о том, что инициализация должна идти впереди создания инстанса.

**Comment by drnextgis** [comment]
В треде говорят, что оба способа рабочие. Тот который используется сейчас у нас - он из cookbook, но Larry Shaffer запилил какую-то штуку, после чего на мастере QGIS рендеринг, сделанный по cookbook-у у нас не работает. Предлагается другой вариант, который якобы все и используют, а cookbook надо поправить, но он у меня не заработал, может я что не так сделал?

**Comment by yellow-sky** [comment]
А у нас работает с мастером?
Вроде же только 2.8?

30 ноября 2015 г., 10:26 пользователь Denis Rykov <notifications@github.com>
написал:

> В треде говорят, что оба способа рабочие. Тот который используется сейчас
> у нас - он из cookbook, но Larry Shaffer запилил какую-то штуку, после чего
> на мастере QGIS рендеринг, сделанный по cookbook-у у нас не работает.
> Предлагается другой вариант, который якобы все и используют, а cookbook
> надо поправить, но он у меня не заработал, может я что не так сделал?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/nextgisweb_qgis/issues/3#issuecomment-160543710>
> .
>



-- 

Best regards,

Nikulin Eugeny

**Comment by drnextgis** [comment]
Я пробую на 2.8

**Comment by drnextgis** [comment]
Исправлено в https://github.com/nextgis/nextgisweb_qgis/commit/82ca1b8b9d6b0c106692f3d5daa138cc5067280c
