### ISSUE TITLE
На чистой Ubuntu Server в подписях нет русских букв

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisweb_qgis#7]
Надо описать, как ставить русские шрифты.

**Comment by drnextgis** [comment]
Проблема не в шрифтах, я сталкивался с подобным явлением, но локально воспроизвести не смог. Если попробуешь запустить интерактивно от обычного пользователя через тот же `pserve`, то всё работает нормально.

**Comment by trolleway** [comment]
Действительно, если запустить pserve вручную, то буквы выводятся

**Comment by dezhin** [comment]
А зависимость от переменных окружения проверяли или нет?

**Comment by trolleway** [comment]
Не проверяли. Pserve я запустил без virtualenv

**Comment by liarsd** [comment]
Извечной проблемой убунту является проблемная локализация, для корректной установки продукта рекомендуем внести некоторые правки в конфиг локали:

sudo nano /etc/default/locale

LANG="ru_RU.UTF-8"
LANGUAGE="ru_RU.UTF-8"
LC_ALL="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"

статья по разворачиванию вашего сервера на https://itg.by/linux/282-nextgis

**Comment by drnextgis** [comment]
Действительно, дело было в переменных окружения. При использовании uWSGI нужно дописать в конфиге:

```
environment = LC_ALL="en_US.UTF-8"
```
