### ISSUE TITLE
Wrong rules calculation with QGIS renderer and Cyrillic attribute names

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisweb_qgis#9]
Reproduce:

VIew in QGIS: 
![image](https://cloud.githubusercontent.com/assets/4630662/15593966/cb120b0c-23b9-11e6-8bab-bc28fe1f59fa.png)
Style settings:
![image](https://cloud.githubusercontent.com/assets/4630662/15593968/de30a2b6-23b9-11e6-9b6e-bf8ac5b788e0.png)

View in nextgis.com, with QGIS rendering:
![image](https://cloud.githubusercontent.com/assets/4630662/15593982/f70852c0-23b9-11e6-8c5e-e5f3207e4432.png)

**Comment by dezhin** [comment]
There was same issue in nextgisweb repository. Now it's fixed in 2.x version of nextgisweb_qgis but also may work in 1.x.
